### ISSUE TITLE
Dropdown no link de locais no menu 

### ISSUE THREAD

**Issue by pedromarins** [horaextra/horaextra.github.com#1]
Dropdown com cada cidade onde está rolando o #horaextra

**Comment by joelwallis** [comment]
Quatro anos de issue! :D Dá até pra fazer aniversário em um HE! Hehe

Acho que não precisa de um dropdown. O formato atual, com uma listagem simples dos eventos, já é suficiente, não?

**Comment by tauil** [comment]
Concordo em fechar essa issue. Isso deve mudar tb com o andar dessa issue #29
