### ISSUE TITLE
Ainda acontece?

### ISSUE THREAD

**Issue by luismacena** [horaextra/horaextra.github.com#27]
Queria saber se ainda acontece esses encontros no Rio.

**Comment by lunks** [comment]
Até onde eu sei o pessoal anda meio parado, @luismacena. Alguém mais pode confirmar?

**Comment by aoqfonseca** [comment]
Luis,

ainda rola. O pessoal da Barra da Tijuca tem sido mais frequente.   O
pessoal do centro da cidade acaba se reunindo menos e quase que só em
convocações especiais.  Mas puxa uma chamada aí que pode ser que o pessoal
compareça

2016-06-15 14:08 GMT-03:00 Pedro Nascimento <notifications@github.com>:

> Até onde eu sei o pessoal anda meio parado, @luismacena
> <https://github.com/luismacena>. Alguém mais pode confirmar?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/horaextra/horaextra.github.com/issues/27#issuecomment-226253703>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAE-GnjNefdLZp67kRZfU8zA0qMd3aMdks5qMDF5gaJpZM4I2khk>
> .
>



-- 
----------------------
Andre Fonseca
http://andrefonseca.net

**Comment by luismacena** [comment]
Eu trabalho em botafogo, tô pensando em fazer por aqui.

**Comment by aoqfonseca** [comment]
Em botafogo é só avisar. Também trabalho em botafogo.

2016-06-17 13:03 GMT-03:00 Luis Felipe Macena <notifications@github.com>:

> Eu trabalho em botafogo, tô pensando em fazer por aqui.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/horaextra/horaextra.github.com/issues/27#issuecomment-226810377>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAE-GmTTfpzFTlbWt6K7zQWJ-V2qU95xks5qMsVvgaJpZM4I2khk>
> .
>



-- 
----------------------
Andre Fonseca
http://andrefonseca.net

**Comment by tauil** [comment]
Em botafogo é só avisar. Também trabalho em botafogo. +1 😄

**Comment by joelwallis** [comment]
Acho que já dá pra fechar esse tópico né! :D No Rio o evento nasceu, aqui em Jampa tá firme e forte *há seis anos* e eu tô ajudando a fundar o Hora Extra Fortaleza.

Hora Extra é um dos melhores formatos que temos por aqui! :D
