### ISSUE TITLE
Tema Jekyll pro Hora Extra

### ISSUE THREAD

**Issue by joelwallis** [horaextra/horaextra.github.com#29]
Fala galera.

Tô vendo que o site do Hora Extra está bem velhinho e queria ajudar. Pensei em fazer um tema Jekyll que pudesse ser usado tanto pelo site oficial, horaextra.org, quanto pelas edições locais (no meu caso estou envolvido no Hora Extra João Pessoa e Hora Extra Fortaleza - esse segundo ainda em fase embrionária).

> FYI: o Jekyll 3.x permite que você use uma gem como tema, adicionando direto no Gemfile, e o build vai _fetchear_ e usar o tema ao invés de usar template files locais.

O que acham? Faz sentido?

**Comment by tauil** [comment]
Boa! Se precisar da logo e qualquer outra coisa, dá uma olhada [nesse repo](https://github.com/horaextra/community-stuff). Se a logo do #he não estiver boa resolução, me vise pois eu fiz ela há muito tempo, mas devo ter o fonte em algum BKP aqui.

**Comment by tauil** [comment]
- [ ] Deve ser responsivo;
- [ ] Boa apresentação de todos as iniciativas do Hora-extra (lista ou algo melhor e facil de ver sem dar scroll);

**Comment by joelwallis** [comment]
FYI: tô me ambientando com o código fonte hoje e vou ver se me familiarizo com o que temos hoje pra poder migrar pro Jekyll mais atual. Tô na briga com RVM e Bundler aqui mas farei funcionar.

Pergunta: quem que é responsável pelo DNS do `horaextra.org`? Pensei em fazer algo com subdomínios, tipo `fortal.horaextra.org` ou `jampa.horaextra.org` com entradas A apontando para as landing pages de edições locais. Vocês acham que faz sentido?

O site hoje é basicamente uma lista de pointers em mapas mostrando onde que acontecem os eventos, mas aqui o Hora Extra tá gerando bastante coisa legal (meio que virou o principal ponto de encontro de todas as comunidades locais). Acho que faria sentido termos landing pages de edições locais do Hora Extra, incluindo fotos dos encontros, posts sobre as edições, etc.

**Comment by tauil** [comment]
O responsável por esse domínio é o @mergulhao , mas por agora eu voto eu fazer ao invés de subdomínios, paths, exemplo: `horaextra.org/floripa`.

Isso facilita absurdamente a automação do processo e o resultado final é quase o mesmo.

**Comment by joelwallis** [comment]
Na verdade, trabalhar com paths vai é sobrecarregar um repositório, eliminando a automomia de cada Hora Extra local.

Com paths teríamos que concentrar tudo nesse repositório, e me parece meio óbvio que isso não iria funcionar muito bem. Cada "braço" do Hora Extra tem pequenas diferenças na forma como funciona, se organiza, etc., e acho que esses devem se organizar da forma que achar melhor.

**Comment by tauil** [comment]
Não entedi a dificuldade. O repositório é público. Se precisar mudar qualquer coisa em algum hora-extra especifico é só cada página ser diferente, mas em termos técnicos vc só depende de criar a página no repositório e não de criar um novo subdomínio, não acha?

**Comment by joelwallis** [comment]
@tauil sim, o repositório do horaextra.org é publico, mas os "braços" do Hora Extra são independentes. Eles têm agendas, organizadores e organização, identidades - enfim, estrutura e funcionamento completamente diferentes.

Aos braços do HE não é interessante essa dependência dos organizadores do HE no Rio, visto que a organização e funcionamento do HE JP, por ex., não diz respeito aos organizadores do HE RJ. Isso se repetirá para o HE FOR e/ou para qualquer outro braço do HE no Brasil.

E não é difícil entender e/ou perceber isso. [O site do HE ficou quase um ano parado](https://github.com/horaextra/horaextra.github.com/commits/master), pois ele dependia de um grupo limitado de organizadores/mantenedores. É preciso que os HEs locais se organizem, pois é muita responsa centralizar a organização de todos os HEs do Brasil em um único grupo de organizadores. E isso obviamente se reflete no site, pois esses terão informações sobre os eventos, posts do que rolou, fotos, etc.

**Comment by tauil** [comment]
Eu acho que os responsáveis por cada #he devem ter permissão de commit e merge no repositório. Isso resolveria o problema, não?

**Comment by lunks** [comment]
Também acho que o ideal seria não dividir, mas permitir mais gente ter acesso. Acho legal manter um padrão na página principal, mas cada hora extra poderia fazer qualquer coisa na sua página como no exemplo do @tauil.

**Comment by tauil** [comment]
Encerrando a discussão até que alguém se interesse em dar um upgrade no layout.
