### ISSUE TITLE
Adicionar lista de contribuidores

### ISSUE THREAD

**Issue by pedromarins** [horaextra/horaextra.github.com#3]
Lista de pessoas que contribuem para o projeto, seja com posts ou com commits

**Comment by joelwallis** [comment]
@pedromarins acho que podemos apenas adicionar um link apontando pra [`/contributors`](https://github.com/horaextra/horaextra.github.com/graphs/contributors), já que todo commit adiciona o autor lá :-)

**Comment by tauil** [comment]
Não entendi direito a ideia. É pra gerar uma página com pessoas que contribuem pro #he? Contribuem como? Participando?
