### ISSUE TITLE
Integrar galeria do flickr na home

### ISSUE THREAD

**Issue by pedromarins** [horaextra/horaextra.github.com#4]
Existem várias fotos do #horaextra que não vão para post nenhum. Temos que montar uma galeria com essas fotos.

**Comment by joelwallis** [comment]
@pedromarins quem são os principais organizadores/mantenedores/responsáveis pelo projeto? Podemos criar uma conta no Flickr para tal façanha, e jogar os links das galerias lá. Criamos uma galeria para cada edição, jogamos as fotos lá e adicionamos um link para fotos na página do evento. Que tal?

**Comment by tauil** [comment]
Precisa de uma conta no flickr? Não basta só linkar e copiar derrepente as imagens postadas por terceiros com a hashtag?
