### ISSUE TITLE
Adicionar meta tags dinâmicas

### ISSUE THREAD

**Issue by pedromarins** [horaextra/horaextra.github.com#6]

**Comment by tauil** [comment]
@pedromarins explique-se

**Comment by joelwallis** [comment]
Metatags dinâmicas em um site estático? Seria necessário?

**Comment by tauil** [comment]
Não sei qual a vantagem, mas dá pra fazer cada coisa maravilhosa com Jekyll que eu fiquei curioso com o que o @pedromarins quis sugerir. :smile:

**Comment by joelwallis** [comment]
O que a gente poderia botar era algumas metatags básicas como description, etc., mas a issue ficou meio vaga (tipo, metatags, no plural, sem especificar quais). Acho que se definirmos algumas básicas rola de mandar um PR.
